In [1]:
%load_ext autoreload
%autoreload 2

# BinBVS examples

In [2]:
import numpy as np
import binbvs
import pathlib
from scipy import sparse

### Generate data
Select the first `p0` features to be the 'true' features.
Create the directory for MCMC output.

In [3]:
n = 100000 # number of samples
p = 100 # number of simulated features
p0 = 5 # number of 'true' features - i.e. features that are associated to the outcome

# set the random seed
np.random.seed(1)

# Generate the sparse matrix
X = sparse.random(n,p, density=0.01).tocsc()
X_col_names = [f'gene_{i}' for i in range(p)]

# initialise the outcome variable
y = (X[:,:p0].sum(1)>0).A1.astype(int)

# generate the output directory
out_dir = pathlib.Path('examples_out')
out_dir.mkdir(exist_ok=True)
print('making', out_dir)

making examples_out

### MCMC example
1. Set the MCMC output (MCMC outputs can be large so we require that an output folder be specified)
2. Generate the results

##### Run MCMC using Metropolis-Hastings (rather than Gibbs)

In [4]:
n_rep = 10*p # Number of MCMC iterations


mcmc = binbvs.MCMC(X, X_col_names, y, out_dir, n_rep, use_gibbs=False)

# Run MCMC with initial condition given by a single randomly chosen feature
mcmc.run(r_n_gamma0=1)
display(mcmc.pip_df[:20])

iter: 100, acc=0.040000
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 200, acc=0.035000
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 300, acc=0.023333
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 400, acc=0.017500
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 500, acc=0.014000
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 600, acc=0.011667
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 700, acc=0.010000
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 800, acc=0.008750
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 900, acc=0.007778
written to  examples_out/pip.csv
written to  examples_out/out.pcl
iter: 1000, acc=0.007000
written to  examples_out/pip.csv
written to  examples_out/out.pcl
time taken for 1000 iterations
0:00:13.297226
written to  examples_out/pip.csv
written to  examples_out/out.pcl

         PIP
gene_0   1.0
gene_2   1.0
gene_3   1.0
gene_4   1.0
gene_1   1.0
gene_64  0.0
gene_73  0.0
gene_72  0.0
gene_71  0.0
gene_70  0.0
gene_69  0.0
gene_68  0.0
gene_67  0.0
gene_66  0.0
gene_65  0.0
gene_61  0.0
gene_63  0.0
gene_62  0.0
gene_75  0.0
gene_60  0.0

##### Run MCMC using Gibbs sampling

In [5]:
n_rep = 10 # Number of MCMC iterations is reduced as when Gibbs sampling is used, a single iteration contains an entire sweep of all variables

gibbs = binbvs.MCMC(X, X_col_names, y, out_dir, n_rep, use_gibbs=True)
gibbs.run(r_n_gamma0=1)
display(gibbs.pip_df[:20])

iter: 10, acc=0.100000
written to  examples_out/pip.csv
written to  examples_out/out.pcl
time taken for 10 iterations
0:00:13.555676
written to  examples_out/pip.csv
written to  examples_out/out.pcl

         PIP
gene_0   1.0
gene_2   1.0
gene_3   1.0
gene_4   1.0
gene_1   1.0
gene_64  0.0
gene_73  0.0
gene_72  0.0
gene_71  0.0
gene_70  0.0
gene_69  0.0
gene_68  0.0
gene_67  0.0
gene_66  0.0
gene_65  0.0
gene_61  0.0
gene_63  0.0
gene_62  0.0
gene_75  0.0
gene_60  0.0

### Example using Variational Bayes inference

In [6]:
n_rep = 2 # Two iterations of variational inference attains good results with this simulated data

vb = binbvs.VB(X, X_col_names, y)
vb.run(n_rep)

vb.qpip_df[:20] # note that the column name is named 'qPIP' to emphasise that this is an approximation to the true PIP

0:00:04.610630

                  qPIP
gene_0    1.000000e+00
gene_2    1.000000e+00
gene_3    1.000000e+00
gene_4    1.000000e+00
gene_1    1.000000e+00
gene_94  3.954042e-267
gene_32  4.827377e-271
gene_59  6.034413e-272
gene_91  1.508635e-272
gene_24  3.771668e-273
gene_7   3.771668e-273
gene_28  3.771668e-273
gene_6   2.357393e-274
gene_51  1.473433e-275
gene_50  1.473433e-275
gene_31  9.209347e-277
gene_37  4.604723e-277
gene_20  4.604723e-277
gene_84  2.302386e-277
gene_87  2.878074e-278